import type { Slide } from '../../../types/story';

interface NextStepsSlideProps {
  slide: Slide;
}

interface NextStepsSlideData {
  recommendations: string[];
}

/**
 * NextStepsSlide - Action items based on insights
 */
export default function NextStepsSlide({ slide }: NextStepsSlideProps) {
  const data = slide.data as unknown as NextStepsSlideData;

  return (
    <div className="space-y-8 animate-fade-in">
      {/* Title */}
      <div className="text-center space-y-4">
        <h2 className="text-4xl md:text-5xl font-bold text-text-primary">
          {slide.title}
        </h2>
        <p className="text-text-secondary text-lg">
          Based on the patterns we found, consider these next steps
        </p>
      </div>

      {/* Recommendations */}
      <div className="space-y-4 max-w-2xl mx-auto">
        {data.recommendations.map((rec, i) => (
          <div
            key={i}
            className="flex items-start gap-4 p-5 rounded-xl bg-bg-elevated border border-border-default hover:bg-bg-hover transition-colors"
            style={{ animation: `fade-in-up 0.5s ease-out ${i * 0.1}s both` }}
          >
            <div className="flex-shrink-0 w-8 h-8 rounded-full bg-primary-light text-primary flex items-center justify-center font-bold">
              {i + 1}
            </div>
            <div className="text-text-primary leading-relaxed pt-0.5">
              {rec}
            </div>
          </div>
        ))}
      </div>

      {/* Footer */}
      <div className="text-center pt-6">
        <p className="text-text-tertiary text-sm">
          Press ESC to exit • Generated by Glimpse
        </p>
      </div>
    </div>
  );
}
